repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Import Sorting
        args: [ "--profile", "black", "--filter-files", "--line-length", "120" ]
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        name: Black
  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
      - id: flake8
        name: Flake8
        args: [ "--max-line-length", "120" ]

